sonar.projectKey=POS-FRONTEND-NEXT
sonar.projectName=POS-FRONTEND-NEXT
sonar.projectVersion=1.0
 
sonar.sources=app
sonar.sourceEncoding=UTF-8
 
# JS/TS config
sonar.language=js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
 
# Exclusions (important for Next.js)
sonar.exclusions=node_modules/**,.next/**,out/**,build/**
 
# Optional: Test files
sonar.tests=app
sonar.test.inclusions=**/*.test.js,**/*.test.tsx
